### ISSUE TITLE
Problem  with using Trezor   &  Suggestion for  vote , challenge and remove in everest 

### ISSUE THREAD

**Issue by SilasZhr** [graphprotocol/mission-control-curator#238]
1. While I add project with metamask  & trezor , there is a problem that  there is no response after  approve sign. I don't konw  that happened because of everest js, contract or metamask; But I could add project correctly with  metamask only. 
2. Someone cannot vote on open challenges, and they just need to add a project first. So I suggest that the UI could add some tips?
https://github.com/graphprotocol/everest/issues/193

**Comment by kaloyan-raev** [comment]
I just tried adding a project using Metamask + Trezor. As stated above, there is no response after approving the sign request. I found this error in the console:

```
Error adding a project:  Error: Network error: MetaMask Message Signature: Error: Not supported on this device
    at new t (bundle.esm.js:50:7)
    at Object.error (bundle.esm.js:1320:58)
    at m (Observable.js:168:108)
    at k (Observable.js:204:5)
    at e.value (Observable.js:257:36)
    at bundle.esm.js:1096:38
    at Set.forEach (<anonymous>)
    at Object.error (bundle.esm.js:1095:27)
    at m (Observable.js:168:108)
    at k (Observable.js:204:5)
```
It would be nice to warn users that Metamask + Hardware Wallet is not supported yet to avoid unnecessary gas fees to deposit DAI in an unsupported wallet.
